default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: webhooks_inbound
  host: 127.0.0.1
  port: 5433

development:
  <<: *default
  database: webhooks_inbound_development

test:
  <<: *default
  database: webhooks_inbound_test

production:
  <<: *default
  database: webhooks_inbound_production
  username: webhooks_inbound
  password:
